name: payments
version: '1.0.0'
config-version: 2
profile: payments

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

clean-targets: ["target", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false
